In [2]:
"""
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.
"""

import numpy as np

def generate_Vandermonde(array,n,order):
    list_of_values = []
    for i in array:
        for j in range(n):
            list_of_values.append(i ** (n-j-1))
    x = np.array(list_of_values).reshape(array.size, n)
    if order == "decreasing":
        return x
    else:
        return x[:,::-1]


array = np.array([1,2,3,4,5,6,7,8])
number = 5
array
print(generate_Vandermonde(array,5,order = "increasing"))
print("-----------------**************--------------------")
print(generate_Vandermonde(array,5,order = "decreasing"))

[[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]
 [   1    7   49  343 2401]
 [   1    8   64  512 4096]]
-----------------**************--------------------
[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]
 [2401  343   49    7    1]
 [4096  512   64    8    1]]


In [11]:
"""
Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
"""

import numpy as np
def func(x, num) :
    arr = np.cumsum(x, dtype=float)
    arr[num:] = arr[num] - arr[:-num]
    return ret[num - 1:] / num
l = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print("output is:")
print(func(l,3))

output is:
[  5.           5.66666667   8.33333333  11.66666667  15.33333333
  37.          61.          88.         121.         154.33333333
 204.33333333]
